# Generated by Django 3.2 on 2021-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
